# Easy alias to get back to the vagrant synced directory
alias rr='cd /apprentice'
alias rs='bundle exec rails s Puma'
alias rails='cd rails-api'
alias react='cd react-app'

# Start off in the vagrant synced directory
cd /apprentice

# Set required 'DISPLAY" variable for xvfb
export DISPLAY=:10

# Set NLS_LANG to tell ruby-oci8 the Oracle client character set
export NLS_LANG=AMERICAN_AMERICA.US7ASCII
